import Group from '~/types/Group';

export const groupStore = {
	id: 1,
	name: '',
	slug: '',
	course: 1,
	days: [
		{
			id: 1,
			name: 'Понедельник',
			lessons: [
				{
					id: 1,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 2,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 3,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 4,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 5,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
			],
		},
		{
			id: 2,
			name: 'Вторник',
			lessons: [
				{
					id: 6,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 7,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 8,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 9,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 10,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
			],
		},
		{
			id: 3,
			name: 'Среда',
			lessons: [
				{
					id: 11,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 12,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 13,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 14,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 15,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
			],
		},
		{
			id: 4,
			name: 'Четверг',
			lessons: [
				{
					id: 16,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 17,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 18,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 19,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 20,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
			],
		},
		{
			id: 5,
			name: 'Пятница',
			lessons: [
				{
					id: 21,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 22,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 23,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 24,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 25,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
			],
		},
		{
			id: 6,
			name: 'Суббота',
			lessons: [
				{
					id: 26,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 27,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 28,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 29,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
				{
					id: 30,
					oddDiscipline: { id: 1, name: 'пусто' },
					evenDiscipline: { id: 1, name: 'пусто' },
					firstOddCabinet: { id: 1, name: 'пусто' },
					secondOddCabinet: { id: 1, name: 'пусто' },
					firstEvenCabinet: { id: 1, name: 'пусто' },
					secondEvenCabinet: { id: 1, name: 'пусто' },
					firstOddTeacher: { id: 1, name: 'пусто' },
					secondOddTeacher: { id: 1, name: 'пусто' },
					firstEvenTeacher: { id: 1, name: 'пусто' },
					secondEvenTeacher: { id: 1, name: 'пусто' },
				},
			],
		},
	],
	changes: [
		{
			id: 21,
			oddDiscipline: { id: 1, name: 'пусто' },
			evenDiscipline: { id: 1, name: 'пусто' },
			firstOddCabinet: { id: 1, name: 'пусто' },
			secondOddCabinet: { id: 1, name: 'пусто' },
			firstEvenCabinet: { id: 1, name: 'пусто' },
			secondEvenCabinet: { id: 1, name: 'пусто' },
			firstOddTeacher: { id: 1, name: 'пусто' },
			secondOddTeacher: { id: 1, name: 'пусто' },
			firstEvenTeacher: { id: 1, name: 'пусто' },
			secondEvenTeacher: { id: 1, name: 'пусто' },
		},
		{
			id: 22,
			oddDiscipline: { id: 1, name: 'пусто' },
			evenDiscipline: { id: 1, name: 'пусто' },
			firstOddCabinet: { id: 1, name: 'пусто' },
			secondOddCabinet: { id: 1, name: 'пусто' },
			firstEvenCabinet: { id: 1, name: 'пусто' },
			secondEvenCabinet: { id: 1, name: 'пусто' },
			firstOddTeacher: { id: 1, name: 'пусто' },
			secondOddTeacher: { id: 1, name: 'пусто' },
			firstEvenTeacher: { id: 1, name: 'пусто' },
			secondEvenTeacher: { id: 1, name: 'пусто' },
		},
		{
			id: 23,
			oddDiscipline: { id: 1, name: 'пусто' },
			evenDiscipline: { id: 1, name: 'пусто' },
			firstOddCabinet: { id: 1, name: 'пусто' },
			secondOddCabinet: { id: 1, name: 'пусто' },
			firstEvenCabinet: { id: 1, name: 'пусто' },
			secondEvenCabinet: { id: 1, name: 'пусто' },
			firstOddTeacher: { id: 1, name: 'пусто' },
			secondOddTeacher: { id: 1, name: 'пусто' },
			firstEvenTeacher: { id: 1, name: 'пусто' },
			secondEvenTeacher: { id: 1, name: 'пусто' },
		},
		{
			id: 24,
			oddDiscipline: { id: 1, name: 'пусто' },
			evenDiscipline: { id: 1, name: 'пусто' },
			firstOddCabinet: { id: 1, name: 'пусто' },
			secondOddCabinet: { id: 1, name: 'пусто' },
			firstEvenCabinet: { id: 1, name: 'пусто' },
			secondEvenCabinet: { id: 1, name: 'пусто' },
			firstOddTeacher: { id: 1, name: 'пусто' },
			secondOddTeacher: { id: 1, name: 'пусто' },
			firstEvenTeacher: { id: 1, name: 'пусто' },
			secondEvenTeacher: { id: 1, name: 'пусто' },
		},
		{
			id: 25,
			oddDiscipline: { id: 1, name: 'пусто' },
			evenDiscipline: { id: 1, name: 'пусто' },
			firstOddCabinet: { id: 1, name: 'пусто' },
			secondOddCabinet: { id: 1, name: 'пусто' },
			firstEvenCabinet: { id: 1, name: 'пусто' },
			secondEvenCabinet: { id: 1, name: 'пусто' },
			firstOddTeacher: { id: 1, name: 'пусто' },
			secondOddTeacher: { id: 1, name: 'пусто' },
			firstEvenTeacher: { id: 1, name: 'пусто' },
			secondEvenTeacher: { id: 1, name: 'пусто' },
		},
	],
} as Group;
